[versions]
project = "4.2.13"
forge = "1.19-41.1.0"
yarn_mappings = "1.19+build.4"
parchment = "2022.08.14-1.19.2"

[libraries]
# Minecraft
minecraft_v19 = { module = "com.mojang:minecraft", version = "1.19" }

# Fabric
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version = "0.58.0+1.19" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version = "0.14.19" }

# Velocioty
velocity = { module = "com.velocitypowered:velocity-api", version = "3.1.2-SNAPSHOT" }

# Spigot
spigot = { module = "org.spigotmc:spigot-api", version = "1.8-R0.1-SNAPSHOT" }

# Sponge
sponge = { module = "org.spongepowered:spongeapi", version = "7.4.0" }

# Utils
lombok = { module = "org.projectlombok:lombok", version = "1.18.22" }
gson = { module = "com.google.code.gson:gson", version = "2.8.8" }
reflections = { module = "org.reflections:reflections", version = "0.10.2" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version = "23.1.0" }

# APIs
luckperms = { module = "net.luckperms:api", version = "5.4" }

# LightDream
lightdream_logger = { module = "dev.lightdream:logger", version = "3.2.0" }
lightdream_lambda = { module = "dev.lightdream:lambda", version = "4.0.0" }
lightdream_messagebuilder = { module = "dev.lightdream:message-builder", version = "3.1.2" }


