name: Build

on: [ push ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup codebase
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1

      - name: Execute Gradle build
        run: gradle build

      - name: Set version env variable
        run: |
          cd Spigot
          echo "VERSION_SPIGOT=$(gradle properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV
          echo "ARTIFACT_SPIGOT=$(gradle properties -q | grep "name:" | awk '{print $2}')" >> $GITHUB_ENV
          
          cd ../Sponge
          echo "VERSION_SPONGE=$(gradle properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV
          echo "ARTIFACT_SPONGE=$(gradle properties -q | grep "name:" | awk '{print $2}')" >> $GITHUB_ENV
          
          cd ../Forge_1_19_3
          echo "VERSION_FORGE_1_19_3=$(gradle properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV
          echo "ARTIFACT_FORGE_1_19_3=$(gradle properties -q | grep "name:" | awk '{print $2}')" >> $GITHUB_ENV
          
          cd ../Velocity
          echo "VERSION_VELOCITY=$(gradle properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV
          echo "ARTIFACT_VELOCITY=$(gradle properties -q | grep "name:" | awk '{print $2}')" >> $GITHUB_ENV
          
          cd ..
          echo "GROUP=$(gradle properties -q | grep "group:" | awk '{print $2}')" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | awk -F'/' '{print $2}')" >> $GITHUB_ENV

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "latest"
          files: |
            target/*.jar

      - name: "README.md Render"
        uses: varunsridharan/action-dynamic-readme@main
        with:
          committer_name: "Radu Voinea"
          committer_email: "contact@voienaradu.com"
          commit_message: "Updated README.md versions"
          files: |
            template/README-template.md=README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VERSION_SPIGOT: ${{ env.VERSION_SPIGOT }}
          VERSION_SPONGE: ${{ env.VERSION_SPONGE }}
          VERSION_FORGE_1_19_3: ${{ env.VERSION_FORGE_1_19_3 }}
          VERSION_VELOCITY: ${{ env.VERSION_VELOCITY }}

          ARTIFACT_SPIGOT: ${{ env.ARTIFACT_SPIGOT }}
          ARTIFACT_SPONGE: ${{ env.ARTIFACT_SPONGE }}
          ARTIFACT_FORGE_1_19_3: ${{ env.ARTIFACT_FORGE_1_19_3 }}
          ARTIFACT_VELOCITY: ${{ env.ARTIFACT_VELOCITY }}

          GROUP: ${{ env.GROUP }}
          GITHUB_USERNAME: ${{ github.REPOSITORY_OWNER }}
          REPOSITORY: ${{ github.REPOSITORY }}
          REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}